version: '3.8'
services:
    # A couple of notes about this usage of Vault:
    # 1. The local JSON should only be used in non-prod environments.
    # 2. Requests to Vault will use the token stored in config/.env
    # 3. I would use Docker secrets to distribute in this example, but
    #    it's a feature that's only available to Docker Swarms.
    passwordstore:
        container_name: passwordstore
        image: hashicorp/vault:latest
        restart: always
        ports:
            - "8200"
        environment:
            - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
            - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
        volumes:
            - secrets:/var/secrets
            - ./config/passwordstore_local.json:/vault/config/local.json

    # This is another task that only happens in demonstration.
    # Normally, you would seed the Vault credentials in a more secure way
    #   than pulling from a file stored in a repository (or repo, for short).
    # For that reason, the Dockerfile will only seed Vault if the
    #   file in the repository exists. So remove it for prod and add some persistence.
    build_passwordstore:
        container_name: build_passwordstore
        build: ./docker/build/passwordstore
        depends_on:
            - passwordstore

volumes:
    secrets: